Plugins/60 VM/60 Powered Off VMs.ps1

Added a check to prevent VMs managed by SRM to show in the list.

Update 60 Powered Off VMs.ps1

---

Plugins/60 VM/58 Virtual machines with less hard disks than partitions.ps1

Added a check to prevent VMs managed by SRM to show in the list, because the SRM replica VMs have no hard disks connected.

Update 58 Virtual machines with less hard disks than partitions.ps1

---

Plugins/30 Host/07 Hosts Overcommit State.ps1
vCheckUtils.ps1

Fixed "Attempted to divide by zero." Error.

Fixed "Attempted to divide by zero." Error.

---

Plugins/50 Network/80 DvPG with less than x Ports Free.ps1

General plugin cleanup and formatting. Added a check to prevent static elastic portgroups to be in the output.

Update 80 DvPG with less than x Ports Free.ps1

---

Plugins/40 Datastore/39 Datastore OverAllocation.ps1

Update 39 Datastore OverAllocation.ps1

---

Plugins/40 Datastore/39 Datastore OverAllocation.ps1

Typo in Datastore OverAllocation

Typo in Datastore OverAllocation plugin

---

.gitAttributes
README.md
Select-Plugins.ps1

* Updated .gitattributes file to include line entries for common PowerShell file types
* Updated README.md to fix a few encoding issues
* Updated `Select-Plugins.ps1`
* Added
```
[cmdletbinding()]
param()
```
* Moved comments into proper comment based help block so it can be reviewed via standard PS help    system (EX: C:\PS>.\Get-Help Select-Plugins.ps1 -ShowWindow)
* Removed Write-Host; converted to Write-Warning

Minor changes; initial PR to dev branch

---

Plugins/20 Cluster/18 Cluster Slot Sizes.ps1

Added type check as slots are only valid for "hosts failures the cluster tolerates" admission control policy.

Fixes #292

---

Plugins/20 Cluster/71 Capacity Planning.ps1

Update 71 Capacity Planning.ps1, Fixes #342, Fixes #234

---

Plugins/60 VM/200 VMs on ephemeral portgroup.ps1

Report all VMs attached to vDS Portgroups with ephemeral binding configured.

VMs on ephemeral portgroup.ps1

---

Plugins/00 Initialize/00 Connection Plugin for vCenter.ps1

Display/Output Servername ($Server) for more clarity

Update 00 Connection Plugin for vCenter.ps1

---

Plugins/20 Cluster/10 HA Configuration Issues.ps1

Make HAIssues configurable by user

Update 10 HA Configuration Issues.ps1

---

README.md
SchedulevCheck.ps1
vCheckUtils.ps1

Add a new `Schedule-vCheck` function and instructions on using it.

Scheduling

---

Plugins/40 Datastore/03 Datastore Information.ps1
Plugins/40 Datastore/109 Orphaned VMDK File.ps1.disabled
Plugins/40 Datastore/115 Datastore Clusters with sDRS Disabled.ps1
Plugins/40 Datastore/116 sDRS VM Behavior not Default.ps1
Plugins/40 Datastore/34 Number of VMs per Datastore.ps1
Plugins/40 Datastore/39 Datastore OverAllocation.ps1
Plugins/40 Datastore/59 Datastores with Storage IO Control Disabled.ps1
Plugins/40 Datastore/69 Datastores in Maintenance mode.ps1
Plugins/40 Datastore/70 Datastores with Alarms Disabled.ps1
Plugins/40 Datastore/84 VMDK consistency.ps1.disabled
Plugins/40 Datastore/990 VSAN Capacity Report.ps1
Plugins/40 Datastore/991 VSAN Configuration Maximum Disk Group Per Host Report.ps1
Plugins/40 Datastore/992 VSAN Configuration Maximum Magnetic Disks Per Disk Group Report.ps1
Plugins/40 Datastore/993 VSAN Configuration Maximum Total Magnetic Disks In All Disk Groups Per Host Report.ps1
Plugins/40 Datastore/994 VSAN Configuration Maximum Component Per Host Report.ps1
Plugins/40 Datastore/995 VSAN Configuration Maximum Hosts Per Cluster Report.ps1
Plugins/40 Datastore/996 VSAN Configuration Maximum VMs Per Host Report.ps1
Plugins/40 Datastore/997 VSAN Configuration Maximum VMs Per Cluster Report.ps1
Plugins/50 Network/24 vSwitch with less than x Ports Free.ps1
Plugins/50 Network/80 DvPG with less than x Ports Free.ps1
Plugins/50 Network/98 vSwitch Security.ps1
Plugins/70 Misc/108 SRM RPO Violations.ps1

Next lot of plugins updated to use Get-vCheckSetting

Update Plugins to use Get-vCheckSetting

---

Plugins/30 Host/29 AD Authentication.ps1

Created a new plugin to display Active Directory settings and domain membership status for each host. A screenshot of the output is attached.

Created new plugin 29 AD Authentication.ps1

---

Plugins/00 Initialize/00 Connection Plugin for vCenter.ps1

Making more changes to make it work on PowerCLI Core for Mac and Linux

Starting to update for PowerCLI Core

---

Plugins/00 Initialize/00 Connection Plugin for vCenter.ps1
Plugins/20 Cluster/104 Clusters with no Host Profile.ps1
Plugins/20 Cluster/52 Datastore Consistency.ps1
Plugins/20 Cluster/70 Cluster Node Version.ps1
Plugins/20 Cluster/75 DRS Rules.ps1
Plugins/30 Host/07 Hosts Overcommit State.ps1
Plugins/30 Host/08 Hosts Dead LUN Path.ps1
Plugins/30 Host/110 Host Certificate Expiration Check.ps1
Plugins/30 Host/44 VMKernel Warnings.ps1
Plugins/30 Host/53 Hardware status warnings-errors.ps1
Plugins/30 Host/68 Disk Max Total Latency.ps1
Plugins/30 Host/81 LUN Paths Check.ps1
Plugins/40 Datastore/116 sDRS VM Behavior not Default.ps1
Plugins/60 VM/02 Snapshot Information.ps1
Plugins/60 VM/04 Map disk region event.ps1
Plugins/60 VM/102 VM Logging.ps1
Plugins/60 VM/14 VMs restarted due to Guest OS Error.ps1
Plugins/60 VM/28 Removable Media Connected.ps1
Plugins/60 VM/30 Single Storage VMs.ps1
Plugins/60 VM/37 VM Alarms.ps1
Plugins/60 VM/40 VCB Garbage.ps1
Plugins/60 VM/45 VMs needing snapshot consolidation.ps1
Plugins/60 VM/50 VMs with CPU or Memory Limits Configured.ps1
Plugins/60 VM/62 Unwanted Virtual Hardware.ps1
Plugins/60 VM/66 Misnamed VM.ps1
Plugins/60 VM/76 VM Network State.ps1
vCheckUtils.ps1

- Replacing foreach and %{ on the pipeline with Foreach-Object
- Replace  ?{ with Where-object
We'll get there eventually...

More updates for Linux/Mac

---

CONTRIBUTING.md

Just fixed a couple typos in the document

Update CONTRIBUTING.md fixing a couple typos

---

Plugins/60 VM/40 VCB Garbage.ps1

Renamed plugin title to "Backup Garbage". Moved snapshot names to a setting and added Commvault to defaults. Corrected -contains to -match for regex compare.

Update 40 VCB Garbage.ps1

---

Plugins/30 Host/115 Host Multipath Policy.ps1

New host plugin "115 Host Multipath Policy.ps1" to check the multipath policy (PSP plugin) that hosts are configured to use.

Add plugin to check host multipath policy.

---

Plugins/30 Host/120 Power Management Policy.ps1

New host plugin "120 Power Management Policy.ps1" to check the power management policy that hosts are configured to use.

Add plugin to check host power management policy

---

Plugins/60 VM/30 Single Storage VMs.ps1

Adds a setting to exclude by datastore name. Permanent resolution for what @mezamoe was attempting in #593.

Update 30 Single Storage VMs

---

vCheck.ps1

Reference: https://github.com/PowerShell/PowerShell/commit/be700729d689f7998110a38889b7962e890e387d

Fix Get-Content for PS6

---

Plugins/60 VM/60 Powered Off VMs.ps1

This is my very first contribution to a project, please excuse any errors and omissions.
Added IgnoredVMFolder to ignore specified folders

Plugin 60 Powered Off VMs. Added IgnoredVMFolder filter

---

Plugins/60 VM/201 VMs Hot Add Configuration.ps1
Plugins/70 Misc/108 SRM RPO Violations.ps1

Plugins 108 and 201 were using $VMs instead of $VM
Resolves #660

Fix VM variable in 108 and 201

---

Plugins/60 VM/126 VM Overrides.ps1

Submitting plugin that will list DrsAutomationLevel, HARestartPriority and HAIsolationResponse attributes in VM Overrides

New plugin 126 VM Overrides

---

Plugins/30 Host/126 Host Linkfailures and CRC errors.ps1

This will check ESX hosts for Fibre Channel Link failures and CRC errors on FC enabled HBA cards

Added check "126 Host Linkfailures and CRC errors"

---

Plugins/30 Host/20 ESXi with Technical Support mode enabled.ps1

Bug fix and clean-up to 30 Host/20 ESXi with Technical Support mode enabled.ps1

Issue #713

---

Plugins/20 Cluster/10 HA Configuration Issues.ps1

Issue #728 - Add the option to store plugin variables in an external CSV file

Add feature to store plugin variables in a CSV

---

Plugins/00 Initialize/00 Connection Plugin for vCenter.ps1
Plugins/60 VM/09 Created or cloned VMs.ps1
Plugins/60 VM/123 VM Check for Spectre Mitigation.ps1
Plugins/60 VM/14 VMs restarted due to Guest OS Error.ps1
Plugins/60 VM/49 EVC Mismatch.ps1
Plugins/60 VM/78 Reset VMs.ps1
Plugins/60 VM/85 Snapshot Activity.ps1
vCheck.ps1

Adds a command option to report only VMs which are in a certain vCenter folder. This way individual tenant reports can be created.
Also fixes some minor formatting and Linux Outputfile issues

adds new param "VMFolder" to vCheck

---

Plugins/10 vCenter/82 License Report.ps1
Plugins/30 Host/74 Host - Network Redundancy lost.ps1
Plugins/60 VM/123 VM Check for Spectre Mitigation.ps1
Plugins/60 VM/200 VMs on ephemeral portgroup.ps1

- Fixed the following issues:
- Resolve #745 
- Resolve #744 
- Resolve #749 
- Resolve #750 
- Close #623
- Fixing bugs
- Tested in my homelab

Fixed several reported issues
