alanrenouf/vCheck-vSphere

- vCheck.ps1
Change job plugin paths routine so it still works with PowerShell 2.0
I raised issue #306 to get someone else to fix this but I figured out how to do this myself (I think). Any suggestions you might have are welcome.
> Change job plugin paths routine in vCheck.ps1 so it still works with PowerShell 2.0

- Plugins/20 Cluster/10 HA Configuration Issues.ps1
- Plugins/20 Cluster/55 Clusters with DRS Disabled.ps1
Not having a plugin settings description causes the following error when exporting and importing settings:
```
You cannot call a method on a null-valued expression.
At E:\scripts\vCheck\vCheck.ps1:152 char:28
+             $CurSet = $Split[1].Trim <<<< ()
+ CategoryInfo          : InvalidOperation: (Trim:String) [], RuntimeExcep
tion
+ FullyQualifiedErrorId : InvokeMethodOnNull
```
Added missing descriptions to 'HA Configuration Issues' and 'Clusters with DRS Disabled' plugins.
> Added plugin settings descriptions

- Plugins/10 vCenter/47 vCenter Session Age.ps1
Raised issue #311 to address a missing functionality to report on vCenter session ages. Added a plugin to report on idle sessions with a configurable maximum age. Also you are able to filter out certain users that are expected to stay connected for longer periods of time.
> Adding vCenter session age plugin version 1.0

- vCheckUtils.ps1
Fixing vCheckUtils to output plugins in plain text.
Trimming variables when exporting csv.
> Fixing vCheckUtils to output plugins in plain text

- vCheck.ps1
Where it gets the subfolders of the `.\Plugins\` folder, it was finding both files and folders, then later, it tried to invoke them (I found this because I had a file `.\Plugins\backup.zip` and wondered why every time I ran vCheck, the zip file opened!). My understanding it that now, all plugins should be stored in subfolders, i.e. `.\Plugins\subfolder\plugin.ps1`, any files in `.\Plugins` shuold be ignored. This change accomplishes that.
(This is the first time I've used GitHub, so please let me know if I've done anything wrong :relaxed:)
> Exclude files in plugins dir

- GlobalVariables.ps1
- vCheck.ps1
The setting for `$EmailReportEvenIfEmpty` already existed, but wasn't
implemented in `vCheck.ps1` (see issue #299). This commit implements that functionality, as
well as adding a new setting `$DisplayReportEvenIfEmpty`
> Implemented $EmailReportEvenIfEmpty and $DisplayReportEvenIfEmpty

- Plugins/40 Datastore/34 Number of VMs per Datastore.ps1
Allows filtering of datastores from the query.  Most of our datastores are 4TB fibre channel LUNs, but we have one Tintri storage device that has 474 VMs on it.  That number goes way beyond the 35 VM limit we put in the report for the FC LUNs.
> Update 34 Number of VMs per Datastore.ps1

- Plugins/30 Host/105 Host Profile Compliance.ps1
Minor change to lines 25 and 27. If only one host comes up as conforming to a host profile in a cluster the $VMHosts variable  does not return as an array when the failures are added in line 29. These are then dropped from the report. By forcing the assignment to an array in lines 25 and 27 the add will always work.
> Update 105 Host Profile Compliance.ps1 - for array add failure on 29 if only one conforming host is found in a cluster

- Plugins/60 VM/120 Multi-writer.ps1
- Plugins/60 VM/121 BusSharingMode - Physical and Virtual.ps1
These plugins check if you have shared disks between two or more VMs. In most cases this is a problem because you cannot svMotion the VMs properly and that is why you have to have a special procedure.
> Shared disks between VMs

- Plugins/60 VM/54 Virtual Machines with incorrect OS Configuration.ps1
For some of the appliances is not possible to select an OS from the
dropdown menu.
That is why I added filter for "54 Virtual Machines with incorrect OS
Configuration".
> Add filter for plugin 54

- Plugins/20 Cluster/70 Cluster Node Version.ps1
Update the match string to use an exact match.
Avoids that for example ClusterComputeResource-domain-c5 and ClusterComputeResource-domain-c5865 would match, and give an incorrect result.
> Update 70 Cluster Node Version.ps1

- Plugins/60 VM/122 NonPersistent Disks.ps1
Adds the ability to exclude VMs (by name) from the results of this plug-in.
MasterChiefJon
#	modified:   Plugins/60 VM/122 NonPersistent Disks.ps1
#
> NonPersistent Disks Exclude VMs

- Plugins/00 Initialize/00 Connection Plugin for vCenter.ps1
As requested, pull request for the dev branch (sorry, should have done this the first time)
if (!(get-module -name VMware.VimAutomation.Core -erroraction
silentlycontinue)) added to 00 Connection Plugin for vCenter.ps1
>  Check if PowerCLI module is already added

- Plugins/60 VM/79 Find VMs in Uncontrolled Snapshot Mode.ps1
Modified script to solve issue #217 at my site.  The change was made to search each Datastore for all VMs that have files named like *delta.vmdk* and -*-flat.vmdk.  In doing the file search this way there is only 2 calls per Datastore and only getting the information needed not other files that are not needed.  This eliminates calling Get-Datacenter and retrieving all files for each VM.  The question I would have is in the current script the line 
if ($file.Name -like '*delta.vmdk*' -or $file -like '-*-flat.vmdk') {
Is the 'or' portion of the statement was that meant to be $file or $file.Name?  And based on what is in quotes the file starts with '-' (a hyphen)?
At my site the current version of "79 Find VMs in Uncontrolled Snapshot Mode.ps1" it ran for 2:40:03 and with this version it …
> Update 79 Find VMs in Uncontrolled Snapshot Mode.ps1 Issue #217

- Plugins/60 VM/60 Powered Off VMs.ps1
Adds some information that helps me decide if I want to follow up on the powered off VM.  In particular for us is our VM decommissioning process.  VMs are moved to a folder "decom" and the notes are updated with the deletion date after a 2 week waiting period.
> Update 60 Powered Off VMs.ps1

- Plugins/50 Network/80 DvPG with less than x Ports Free.ps1
- Plugins/50 Network/98 vSwitch Security.ps1
The VMware.VimAutomation.Vds module does not always auto-load on
PowerCLI 6.x.  Added code to check for and import the module-based
cmdlets for newer versions of PowerCLI
> support PowerCLI 6.x

- vCheckUtils.ps1
A missing hyphen caused the New-ScheduledJobOption call to fail.
> Typo in Schedule-vCheck

- Plugins/30 Host/29 AD Authentication.ps1
Added expected AD Domain Name and AD Admin Group settings.
Added setting to display all results. By default only displays failed results.
Improved performance. Run time cut by 2/3 in test environment.
> New features for AD Authentication Plugin

- Plugins/60 VM/49 EVC Mismatch.ps1
Created a plugin to compare the EVC mode of the VM with the EVC mode of the host/cluster. For VMs which do not match the cluster, output the VM name, VM EVC, Host name, Host EVC and Cluster name.
> Create 49 EVC Mismatch.ps1

- Plugins/50 Network/98 vSwitch Security.ps1
A number of logical and formatting fixes to this plugin:
1. Ignore ForgedTransmits on vDS Uplink port groups.
2. Expanded ForEach-Object aliases and ran thru VS Code's formatter.
3. Fixed several logic bugs which prevented some checks from returning expected results.
4. Removed unused $vSwitchSecurityCheck setting and redundant plugin variable block.
5. Fixed the settings logic so a vSwitch or port group only appears if one of the conditions you've selected to report on is true.
> Update 98 vSwitch Security.ps1

- Plugins/30 Host/29 AD Authentication.ps1
- Plugins/30 Host/31 NTP Name and Service.ps1
- Plugins/30 Host/35 Host Configuration Issues.ps1
Fix several plugins which report empty results or errors when hosts are disconnected or not responding. Also normalized some indenting.
> Update some host plugins to report connected hosts only

- Plugins/30 Host/51 Syslog Name.ps1
Adds support for multiple syslog server destinations. Also modified to only report on hosts in Connected state, as disconnected and not responding hosts generate a blank result.
> Add support for multiple syslog servers, only report on connected hosts

- Plugins/30 Host/130 Eval License Key.ps1
Lists hosts that are not licensed and will disconnect from vCenter when the evaluation period expires.
> Add host plugin to detect evaluation licenses

- Plugins/30 Host/125 Host NFS Settings.ps1.disabled
This plugin checks advanced settings related to NFS storage.  I have it disabled by default because the recommended settings can vary based on ESXi version and storage vendor, but for environments that use a lot of NFS attached storage I think it is helpful for identifying misconfigured hosts.
> Add host plugin for NFS storage settings

- Plugins/00 Initialize/00 Connection Plugin for vCenter.ps1
- Plugins/20 Cluster/10 HA Configuration Issues.ps1
- Plugins/30 Host/07 Hosts Overcommit State.ps1
- Plugins/60 VM/32 VM CPU Percent RDY.ps1
- Plugins/60 VM/79 Find VMs in Uncontrolled Snapshot Mode.ps1
- vCheck.ps1
Both Linux and MacOS have case-sensitive filenames.
This fixes the casing of the "\Lang" directory where it's referenced. While it does silently continue there are immediate errors when running `-Config` because of this line: https://github.com/alanrenouf/vCheck-vSphere/blob/dev/vCheck.ps1#L833
> Fix "\Lang" directory casing

- vCheck.ps1
system.net.mail.LinkedResource doesn't like non-native paths such as backslashes on Linux. The Convert-Path cmdlet fixes that.
> Fix LinkedResource with non-native paths

- Plugins/20 Cluster/71 Capacity Planning.ps1
This is a proposal to fix #634.  It also addresses a bug where $MemVmLeft was not being set for clusters with very low memory usage.
> Fix for special characters in cluster name

- Plugins/60 VM/121 BusSharingMode - Physical and Virtual.ps1
Plugin was re-using the $VM variable and therefore rendering it useless for subsequent plugins
> Plugin 121. Fixed bug where it would mess up plugins that came after it

- Plugins/20 Cluster/71 Capacity Planning.ps1
VMware recommends using pCPU cores for ratio calculations, not vCPU threads. (https://communities.vmware.com/thread/572025)
I changed the calculation to include both and edited the descriptions to match.
Fix for issue #676
> 71 Capacity Planning. pCPU thread vs core fix

- Plugins/20 Cluster/40 Cluster Overcommitment Rate.ps1
This plugin calculates the rate between the actual existing CPUs and memory to the committed CPUs and memory in the virtual hardware of every VM.
> feat: Added cluster overcommitment rate

- Plugins/60 VM/121 BusSharingMode - Physical and Virtual.ps1
I have tested and when this script is run, the variable $VM (which contains alls VMs) is overwritten by the last VM checked.
I have checked the number of objects in variable $VM and when this script is run, the count is 1 (the last one) causing next scripts to fail (as I only have 1 VM).
> Update script so it will not overwrite variable $VM

- Plugins/60 VM/62 Unwanted Virtual Hardware.ps1
Added ' $ExcludeVM = "vm1|vm2" ' variable and added the filter with ' ($FullVM | Where-Object { $_.Name -notmatch $ExcludeVM }) '.
> Update 62 Unwanted Virtual Hardware.ps1 - Filter VM name

- Plugins/60 VM/48 Find VM Disk Format.ps1
Adding '-DiskType Flat' to Get-Harddisk will improve performance as the data will be filtered in vCenter before being returned to the cmdlet.  As a minor bonus, it will also reduce output noise to the screen.  An error is generated for any non-flat disks because they don't have the StorageFormat property.
> Update 48 Find VM Disk Format.ps1 - Filter Disktype

- Plugins/00 Initialize/00 Connection Plugin for vCenter.ps1
- Plugins/30 Host/126 Host Linkfailures and CRC errors.ps1
- vCheck.ps1
This fixes setting up a credential file. If file does not exist, user will be asked for credentials and credential file will be created.
If a credential exists, credentials from file will be used.
Also the initial config is working again. This got broken with previous commits.
> fixes setting up credentials and logic of initial setup

- Plugins/30 Host/46 Missing ESX patches.ps1
- Fix Missing ESX patches plugin out of date and broken issue
- Re-enable the ability to obtain missing patches from Esxi
- Tested in my homelab
> Fix Missing ESX patches plugin out of date and broken #623

- Plugins/00 Initialize/00 Connection Plugin for vCenter.ps1
- Plugins/00 Initialize/01 General Information.ps1
- Plugins/10 vCenter/23 VI Events.ps1
- Plugins/20 Cluster/17 DRS Migrations.ps1
Optimized DRS and SDRS queries in 01 General Info and 17 DRS Migrations (Issue #695).
This brought my vCheck runtime from 103.56 minutes to 44.64 minutes in a vSphere 7.0U3 environment.
General Information runtime from 2111.82 seconds to 13 seconds.
DRS & SDRS Migrations runtime from 1009.88 seconds to <1 second.
Optimized Get-VIEventPlus by swapping from an array to a list for faster inserts. Also added EventCategory parameter as mentioned in Issue #705 along with fixing 23 VI Events to use the EventCategory parameter.
I tested these changes on a vSphere 7.0U3 environment with 59 hosts and 962 VMs.
> Issue Fix 695 and 705

- Plugins/40 Datastore/84 VMDK consistency.ps1.disabled
Fixed an issue preventing the plugin from exiting gracefully on error and wrecking the rest of the vCheck run.
> Update 84 VMDK consistency.ps1.disabled
